version: '3.8'
services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
